[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.127.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc -D"

[[redirects]]
  from = "/index.xml"
  to = "/"
  status = 301

[dev]
  framework = "#static"
  targetPort = 1313
  port = 8888
  command = "hugo server -D --bind=0.0.0.0 --port 1313"
